#cloud-config

package_update: true
package_upgrade: false

packages:
  - python3-pip
  - python3-venv
  - git

users:
  - name: jupyter
    groups:
      - sudo
    home: /home/jupyter
    shell: /bin/bash
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

runcmd:
  # Make sure jupyter owns its home directory
  - chown -R jupyter:jupyter /home/jupyter

  # Create Python virtual environment
  - runuser -u jupyter -- bash -c "python3 -m venv /home/jupyter/venv"

  # Clone your Git repository
  - runuser -u jupyter -- bash -c "git clone https://github.com/dpmcnevin/C964 /home/jupyter/C964"
  -
  # Upgrade pip and install required Python packages
  - runuser -u jupyter -- bash -c "/home/jupyter/venv/bin/pip install --upgrade pip"
  - runuser -u jupyter -- bash -c "/home/jupyter/venv/bin/pip install -r /home/jupyter/C964/requirements.txt"

  # Start Jupyter Server
  - runuser -u jupyter -- bash -c "cd /home/jupyter/C964 && /home/jupyter/venv/bin/marimo run C964_Daniel_McNevin.py --host=0.0.0.0 --port=8888 --headless --no-token &"
